# Generated by Django 5.0.7 on 2025-07-06 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('پیش غذا', 'پیش غذا'), ('غذای اصلی', 'غذای اصلی'), ('دسر', 'دسر')], default='غذای اصلی', max_length=20)),
                ('name', models.CharField(max_length=70, verbose_name='اسم')),
                ('slug', models.SlugField(default='', max_length=70)),
                ('description', models.CharField(max_length=250, verbose_name='توضیحات')),
                ('rate', models.IntegerField(default=100, verbose_name='امتیاز')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('time', models.IntegerField(verbose_name='زمان لازم')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('photo', models.ImageField(upload_to='foods/', verbose_name='عکس')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.cart')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.food')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='menu.CartItem', to='menu.food'),
        ),
    ]
